on:
  push:
    branches: [ "stable" ]
jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      sarifGenerator: opengrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run SOOS SAST Docker CLI Scan
        run: |
          docker pull soosio/sast
          docker run -u soos -v ${{ github.workspace }}:/home/soos/wrk/:rw --rm soosio/sast --sarifGenerator $sarifGenerator --apiURL="https://qa-api.soos.io/api/" --clientId=${{ secrets.SOOS_CLIENT_ID }} --apiKey=${{ secrets.SOOS_API_KEY }} --projectName="SAST-Docker-CLI in GitHub Actions"
